modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="frozenup"
version="1.19.2-1.0.0"
displayName="Frozen Up"
logoFile= "frozenup.png"
authors="Ninni"
description='''
Frozen Up is a small mod that adds a bunch of new snowy features while keeping in mind the classic minecraft feel.
'''
[[dependencies.frozenup]]
modId="forge"
mandatory=true
versionRange="[39,)"
ordering="NONE"
side="BOTH"
[[dependencies.frozenup]]
modId="minecraft"
mandatory=true
versionRange="[1.19,1.20)"
ordering="NONE"
side="BOTH"