modLoader="javafml"
loaderVersion="[39,)"
license="All rights reserved"
[[mods]]
modId="frozenup"
version="2.1.2-forge"
displayName="Frozen Up"
logoFile= "frozenup.png"
authors="Ninni, Coda1552, superlord9362, Mr. Esuoh, andante., Orcinus"
description='''
Frozen Up is a small mod that adds a bunch of new snowy features while keeping in mind the classic minecraft feel.
'''
[[dependencies.frozenup]]
modId="forge"
mandatory=true
versionRange="[39,)"
ordering="NONE"
side="BOTH"
[[dependencies.frozenup]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"